name: campus_app
description: Simplifie, improve and facilitate everyday students life.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.5
  flutter_secure_storage: ^4.2.1
  provider: ^6.0.3
  auto_route: ^3.2.4
  cached_network_image: ^3.2.0
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  get_it: ^7.2.0
  html: ^0.15.0
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.11
  pdfx: ^2.0.1+2
  xml: ^5.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.8  
  flutter_lints: ^1.0.0
  mockito: ^5.1.0

flutter:
  assets:
     - assets/img/
     - assets/documents/
  #fonts:
  #  - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  uses-material-design: true
  generate: true
